import type {
  FlightOrderCrossSellData,
  FlightOrderCrossSellProps,
} from './types'

type FlightOrderCrossSellSampleData = Omit<
  FlightOrderCrossSellProps,
  'hsrAddon' | 'promo' | 'reminders'
> &
  Pick<FlightOrderCrossSellData, 'hsrAddon' | 'promo' | 'reminders'>

const activeStartsAt = new Date(
  Date.now() - 15 * 24 * 60 * 60 * 1000,
).toISOString()
const popularSearchBaseUrl = 'https://www.liontravel.com/search'
const sampleImageUrls = {
  airportTransfer:
    'https://picsum.photos/seed/liontravel-airport-transfer/640/426',
  cityHotel: 'https://picsum.photos/seed/liontravel-city-hotel/640/426',
  familyStay: 'https://picsum.photos/seed/liontravel-family-stay/640/426',
  hotelBay: 'https://picsum.photos/seed/liontravel-tokyo-bay-hotel/640/426',
  hotelLounge: 'https://picsum.photos/seed/liontravel-hotel-lounge/640/426',
  hotelRoom: 'https://picsum.photos/seed/liontravel-hotel-room/640/426',
  railPass: 'https://picsum.photos/seed/liontravel-rail-pass/640/426',
  seasideHotel: 'https://picsum.photos/seed/liontravel-seaside-hotel/640/426',
  themePark: 'https://picsum.photos/seed/liontravel-theme-park/640/426',
  tokyoCulture: 'https://picsum.photos/seed/liontravel-tokyo-culture/640/426',
  tokyoRail: 'https://picsum.photos/seed/liontravel-tokyo-rail/640/426',
  travelPass: 'https://picsum.photos/seed/liontravel-travel-pass/640/426',
}

function createPopularSearchUrl(keyword: string) {
  const searchParams = new URLSearchParams({ keyword })

  return `${popularSearchBaseUrl}?${searchParams.toString()}`
}

// Storybook and tests use this fixture to exercise the widget's default content resolver.
export const flightOrderCrossSellSampleData: FlightOrderCrossSellSampleData = {
  locale: 'zh-TW',
  currency: 'TWD',
  domainMode: 'uat',
  order: {
    orderYear: '2026',
    orderNumber: '16575',
  },
  serviceAgent: {
    email: 'customer-service@liontravel.com',
  },
  promo: {
    id: 'limited-offer',
    activeTitle: '您已解鎖限時優惠！',
    expiredTitle: '發現更多旅遊靈感！',
    startsAt: activeStartsAt,
    durationSeconds: 30 * 24 * 60 * 60,
    serviceLabel: '加訂住宿、高鐵與票券享專屬折扣',
    benefits: [
      {
        id: 'addon-discount',
        tagLabel: '加購價',
        label: '最高可省 25%',
      },
      {
        id: 'flight-change-cancel',
        label: '航班異動可免費取消',
      },
    ],
  },
  hsrAddon: {
    id: 'hsr',
    title: '加購高鐵 行程更順暢',
    description: '購買國內外行程，最高享 8 折優惠',
    ctaLabel: '前往加購',
  },
  reminders: {
    title: '別忘了加購一份安心與便利',
    subtitle: '即將出門？',
    items: [
      {
        id: 'visa-passport',
        icon: 'passport',
        title: '簽證護照',
        description:
          '受理代辦中華民國護照、台胞證、各國簽證、國際學生證辦理等，雄獅帶你輕鬆玩遍全球。',
      },
      {
        id: 'travel-insurance',
        icon: 'insurance',
        title: '旅遊綜合險',
        description:
          '於出發前七個工作天聯繫業務專員，為您的旅行提供全方位的保障！',
      },
    ],
  },
  sections: [
    {
      id: 'tokyo-hotels',
      kind: 'hotel',
      items: [
        {
          id: 'la-vista-tokyo-bay',
          title: 'LA VISTA 東京灣',
          imageUrl: sampleImageUrls.hotelLounge,
          location: '距離市場前站0.2公里',
          detailLocation: '江東區',
          badge: '熱銷 TOP1',
          promoBadge: '86%東京旅客喜愛',
          starRating: 5,
          rating: '4.5',
          ratingLabel: '太讚了',
          reviewCount: 1132,
          cancellationLabel: '免費取消',
          originalPrice: 1825,
          discountLabel: '折扣 20%',
          price: 1224152,
          priceSuffix: '起',
        },
        {
          id: 'hotel-metropolitan',
          title: '東京灣舒適飯店',
          imageUrl: sampleImageUrls.hotelRoom,
          location: '江東區',
          detailLocation: '江東區',
          promoBadge: '86%東京旅客喜愛',
          starRating: 5,
          rating: '4.5',
          ratingLabel: '太讚了',
          reviewCount: 1132,
          cancellationLabel: '免費取消',
          originalPrice: 1825,
          discountLabel: '折扣 20%',
          price: 1224152,
          priceSuffix: '起',
        },
        {
          id: 'tokyo-bay-stay',
          title: '東京灣景觀旅宿',
          imageUrl: sampleImageUrls.hotelBay,
          location: '江東區',
          detailLocation: '江東區',
          promoBadge: '86%東京旅客喜愛',
          starRating: 5,
          rating: '4.5',
          ratingLabel: '太讚了',
          reviewCount: 1132,
          cancellationLabel: '免費取消',
          originalPrice: 1825,
          discountLabel: '折扣 20%',
          price: 1224152,
          priceSuffix: '起',
        },
        {
          id: 'market-front-hotel',
          title: '市場前站高評價飯店',
          imageUrl: sampleImageUrls.cityHotel,
          location: '距離市場前站0.2公里',
          detailLocation: '江東區',
          promoBadge: '86%東京旅客喜愛',
          starRating: 5,
          rating: '4.5',
          ratingLabel: '太讚了',
          reviewCount: 1132,
          cancellationLabel: '免費取消',
          originalPrice: 1825,
          discountLabel: '折扣 20%',
          price: 1224152,
          priceSuffix: '起',
        },
        {
          id: 'odaiba-hotel',
          title: '台場親子精選飯店',
          imageUrl: sampleImageUrls.seasideHotel,
          location: '江東區',
          detailLocation: '江東區',
          promoBadge: '86%東京旅客喜愛',
          starRating: 5,
          rating: '4.5',
          ratingLabel: '太讚了',
          reviewCount: 1132,
          cancellationLabel: '免費取消',
          originalPrice: 1825,
          discountLabel: '折扣 20%',
          price: 1224152,
          priceSuffix: '起',
        },
        {
          id: 'ginza-design-hotel',
          title: '銀座設計旅店',
          imageUrl: sampleImageUrls.cityHotel,
          location: '銀座',
          detailLocation: '銀座',
          promoBadge: '86%東京旅客喜愛',
          starRating: 5,
          rating: '4.6',
          ratingLabel: '很棒',
          reviewCount: 856,
          cancellationLabel: '免費取消',
          originalPrice: 2410,
          discountLabel: '折扣 18%',
          price: 98600,
          priceSuffix: '起',
        },
        {
          id: 'shinjuku-city-hotel',
          title: '新宿城市飯店',
          imageUrl: sampleImageUrls.hotelRoom,
          location: '新宿區',
          detailLocation: '新宿區',
          promoBadge: '熱門加購',
          starRating: 5,
          rating: '4.4',
          ratingLabel: '太讚了',
          reviewCount: 2041,
          cancellationLabel: '免費取消',
          originalPrice: 3180,
          discountLabel: '折扣 15%',
          price: 112300,
          priceSuffix: '起',
        },
        {
          id: 'ueno-family-stay',
          title: '上野家庭友善旅宿',
          imageUrl: sampleImageUrls.familyStay,
          location: '上野',
          detailLocation: '上野',
          promoBadge: '親子首選',
          starRating: 5,
          rating: '4.3',
          ratingLabel: '很棒',
          reviewCount: 624,
          cancellationLabel: '免費取消',
          originalPrice: 2650,
          discountLabel: '折扣 12%',
          price: 88400,
          priceSuffix: '起',
        },
      ],
    },
    {
      id: 'tokyo-attractions',
      kind: 'attraction',
      subtitle: '大家都在搜尋',
      popularSearches: [
        {
          id: 'tokyo-disney',
          label: '東京迪士尼',
          href: createPopularSearchUrl('東京迪士尼'),
        },
        {
          id: 'universal-studios-japan',
          label: '日本環球影城',
          href: createPopularSearchUrl('日本環球影城'),
        },
        {
          id: 'travel-pass',
          label: '周遊券',
          href: createPopularSearchUrl('周遊券'),
        },
        {
          id: 'japan-esim',
          label: '日本 eSim',
          href: createPopularSearchUrl('日本 eSim'),
        },
        {
          id: 'tokyo-disney-ticket',
          label: '東京迪士尼',
          href: createPopularSearchUrl('東京迪士尼門票'),
        },
        {
          id: 'universal-studios-japan-ticket',
          label: '日本環球影城',
          href: createPopularSearchUrl('日本環球影城門票'),
        },
      ],
      items: [
        {
          id: 'tokyo-disney-ticket',
          title: '東京迪士尼門票東京迪士尼門票',
          imageUrl: sampleImageUrls.themePark,
          location: '江東區',
          badge: '熱銷 TOP1',
          promoBadge: '86%東京旅客喜愛',
          rating: '4.5',
          ratingLabel: '太讚了',
          reviewCount: 1132,
          interestLabel: '200K+人有興趣',
          cancellationLabel: '免費取消',
          originalPrice: 544999,
          discountLabel: '折扣 20%',
          price: 1224152,
          priceSuffix: '起',
        },
        {
          id: 'tokyo-theme-park-pass',
          title: '東京上野門票・景點套票',
          imageUrl: sampleImageUrls.travelPass,
          location: '江東區',
          promoBadge: '86%東京旅客喜愛',
          rating: '4.5',
          ratingLabel: '太讚了',
          reviewCount: 1132,
          interestLabel: '200K+人有興趣',
          cancellationLabel: '免費取消',
          originalPrice: 544999,
          discountLabel: '折扣 20%',
          price: 1224152,
          priceSuffix: '起',
        },
        {
          id: 'tokyo-culture-pass',
          title: '東京上野周邊一日通行票',
          imageUrl: sampleImageUrls.tokyoCulture,
          location: '江東區',
          promoBadge: '86%東京旅客喜愛',
          rating: '4.5',
          ratingLabel: '太讚了',
          reviewCount: 1132,
          interestLabel: '200K+人有興趣',
          cancellationLabel: '免費取消',
          originalPrice: 544999,
          discountLabel: '折扣 20%',
          price: 1224152,
          priceSuffix: '起',
        },
      ],
    },
    {
      id: 'local-transport',
      kind: 'transport',
      items: [
        {
          id: 'narita-express',
          title: '東京成田/羽田機場至東京都市區',
          imageUrl: sampleImageUrls.tokyoRail,
          location: '江東區',
          rating: '4.5',
          ratingLabel: '太讚了',
          reviewCount: 1132,
          interestLabel: '200K+人有興趣',
          cancellationLabel: '免費取消',
          originalPrice: 544999,
          discountLabel: '折扣 20%',
          price: 1224152,
          priceSuffix: '起',
        },
        {
          id: 'tokyo-airport-transfer',
          title: '東京成田/羽田機場接送',
          imageUrl: sampleImageUrls.airportTransfer,
          location: '江東區',
          rating: '4.5',
          ratingLabel: '太讚了',
          reviewCount: 1132,
          interestLabel: '200K+人有興趣',
          cancellationLabel: '免費取消',
          originalPrice: 544999,
          discountLabel: '折扣 20%',
          price: 1224152,
          priceSuffix: '起',
        },
        {
          id: 'tokyo-rail-pass',
          title: '東京周遊交通票券',
          imageUrl: sampleImageUrls.railPass,
          location: '江東區',
          rating: '4.5',
          ratingLabel: '太讚了',
          reviewCount: 1132,
          interestLabel: '200K+人有興趣',
          cancellationLabel: '免費取消',
          originalPrice: 544999,
          discountLabel: '折扣 20%',
          price: 1224152,
          priceSuffix: '起',
        },
      ],
    },
  ],
}
